### ISSUE TITLE
[BUG] Plugin Isnt Valid.

### ISSUE THREAD

**Issue by 68r** [ali-han/arcade-theme#1]
When I try uploading the Plugin for Wordpress with the zip file provided on your website, arcadetheme.com, an error message pops up:

The package could not be installed. No valid plugins were found.

Plugin installation failed.

**Comment by ali-han** [comment]
Hello @x4ie 
This is not a plugin. This is a theme. So you need to install it as a theme.
Can you try again?

**Comment by x4ie** [comment]
My bad, Ill try to reinstall the file as soon as I can.

**Comment by ali-han** [comment]
It doesn't matter! I continue to develop the theme. 
I value your feedback.
Thanks.

**Comment by rmgyopensource** [comment]
Now when I activate the theme it says “There is a critical error with your website”, which then I have to delete and reinstall XAMPP and Wordpress just to get Wordpress working again on a blank state. Any tips?

**Comment by ali-han** [comment]
Is that the whole error code?  I need more details...

Also, you don't need to uninstall XAMPP. If problems occur, just remove theme folder: /wp-content/themes/arcade-theme/

**Comment by x4ie** [comment]
**The error code when I go to http://127.0.0.1/wordpress/wp-admin/** :
https://i.gyazo.com/da3c6390a7ce3c73587925df884440f3.png

**The error code when I go to http://127.0.0.1/wordpress/** :
https://i.gyazo.com/25f9ce5787edfe0ded853aaa7058790c.png

I just started using wordpress for arcadetheme so I'm very new to all of this. Im sorry if the answer might seem obvious, but is there anything I could do to solve the issue of these screens appearing when I activate the theme?

**Comment by ali-han** [comment]
Hello.
Please enable debugging. Then try again. So the error will be visible.
https://codex.wordpress.org/WP_DEBUG
