### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by sjogrjot** [ali-han/arcade-theme#3]
Hi I get a parse error when I try to install this theme on the latest wordpress installation.

**Comment by ali-han** [comment]
> Ali bey aynı hatayı almaya devam ediyorum hatta wordpressi kaldırıp yeniden yükledim fakat sorun devam etmekte, iyi çalışmalar.

Selamlar, zaten yeni kurulum yapıyorsunuz, bana şu adresten site bilgilerini verir misiniz. birde ben bakayım. Sıkıntıyı çözmeye çalışayım: https://arcadetheme.com/contact-us/

**Comment by ali-han** [comment]
> Ali bey aynı hatayı almaya devam ediyorum hatta wordpressi kaldırıp yeniden yükledim fakat sorun devam etmekte, iyi çalışmalar.

Dönüş yaptığın için teşekkür ederim Hakkı bey. Geliştirme aşamasında artık destek verilmeyen "short open tags" kodları kalmış. Onları temizledim. Sitenize de bir kaç ayar yaptım. Ama oyunların düzgün çalışması için sizin de gamemonetize ve gamedist sitelerine sitenizi kaydedip ads.txt dosyanızı oluşturmanız gerekiyor. gerekli açıklamalar oyun sağlayan sitelerde mevcut. 
iyi çalışmalar.

**Comment by ustahakki** [comment]
Çok teşekkür ederim Ali bey, oyun sitelerine sitemi ekleyeceğim bir başka sitemde oralarda ekli zaten ilginiz ve anlayışınız için teşekkür ederim, iyi çalışmalar.
