### ISSUE TITLE
how can i download this theme please 

### ISSUE THREAD

**Issue by Hazembisha** [ali-han/arcade-theme#5]
Hi 

Thanks for this theme
i have check arcadetheme.com website and download link doesn't work 
How can i download it please 

Thanks

**Comment by ali-han** [comment]
You can download it here. If this version is out of date, check the WordPress updates page.
The theme version syncs with our server.
[arcade-theme_latest.zip](https://github.com/ali-han/arcade-theme/files/10568998/arcade-theme_latest.zip)
